server:
  port: 8761

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    registry-fetch-interval-seconds: 30
    registerWithEureka: false
    fetchRegistry: false
  server:
    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.85

spring:
  application:
    name: eureka-server
